<?php

return [
    'super_admin' => [
        'name' => env('SUPER_ADMIN_NAME', 'Super Admin'),
        'email' => env('SUPER_ADMIN_EMAIL', 'admin@shop.local'),
        'phone' => env('SUPER_ADMIN_PHONE', '0900000001'),
        'password' => env('SUPER_ADMIN_PASSWORD', 'password123'),
    ],

    'permissions' => [
        [
            'key' => 'admin.dashboard.view',
            'name' => 'View dashboard',
            'group' => 'Dashboard',
            'description' => 'View admin dashboard metrics and queues.',
        ],
        [
            'key' => 'admin.community.view',
            'name' => 'View community',
            'group' => 'Community',
            'description' => 'View community and supplier invitation data.',
        ],
        [
            'key' => 'admin.community.invitation.create',
            'name' => 'Create supplier invitations',
            'group' => 'Community',
            'description' => 'Create supplier invitation records.',
        ],
        [
            'key' => 'admin.community.posts.view',
            'name' => 'View posts',
            'group' => 'Community',
            'description' => 'View admin post data.',
        ],
        [
            'key' => 'admin.community.posts.create',
            'name' => 'Create posts',
            'group' => 'Community',
            'description' => 'Create community posts.',
        ],
        [
            'key' => 'admin.community.posts.update',
            'name' => 'Update posts',
            'group' => 'Community',
            'description' => 'Update community posts and publish status.',
        ],
        [
            'key' => 'admin.community.posts.delete',
            'name' => 'Delete posts',
            'group' => 'Community',
            'description' => 'Delete community posts.',
        ],
        [
            'key' => 'admin.community.comments.moderate',
            'name' => 'Moderate post comments',
            'group' => 'Community',
            'description' => 'Hide or restore customer comments on posts.',
        ],
        [
            'key' => 'admin.settings.view',
            'name' => 'View admin settings',
            'group' => 'Settings',
            'description' => 'View admin settings for the current account.',
        ],
        [
            'key' => 'admin.settings.update',
            'name' => 'Update admin settings',
            'group' => 'Settings',
            'description' => 'Update admin settings for the current account.',
        ],
        [
            'key' => 'admin.users.view',
            'name' => 'View users',
            'group' => 'Users',
            'description' => 'View customer accounts in the admin user directory.',
        ],
        [
            'key' => 'admin.users.create',
            'name' => 'Create users',
            'group' => 'Users',
            'description' => 'Create customer accounts from the admin user directory.',
        ],
        [
            'key' => 'admin.users.update',
            'name' => 'Update users',
            'group' => 'Users',
            'description' => 'Update customer account profile and status fields.',
        ],
        [
            'key' => 'admin.users.delete',
            'name' => 'Delete users',
            'group' => 'Users',
            'description' => 'Block customer accounts without removing their order history.',
        ],
        [
            'key' => 'admin.products.view',
            'name' => 'View products',
            'group' => 'Catalog',
            'description' => 'View products in the admin catalog.',
        ],
        [
            'key' => 'admin.products.create',
            'name' => 'Create products',
            'group' => 'Catalog',
            'description' => 'Create products in the admin catalog.',
        ],
        [
            'key' => 'admin.products.update',
            'name' => 'Update products',
            'group' => 'Catalog',
            'description' => 'Update products and product status.',
        ],
        [
            'key' => 'admin.products.delete',
            'name' => 'Delete products',
            'group' => 'Catalog',
            'description' => 'Delete products when no related data exists.',
        ],
        [
            'key' => 'admin.categories.create',
            'name' => 'Create categories',
            'group' => 'Catalog',
            'description' => 'Create catalog categories.',
        ],
        [
            'key' => 'admin.categories.update',
            'name' => 'Update categories',
            'group' => 'Catalog',
            'description' => 'Update catalog categories.',
        ],
        [
            'key' => 'admin.categories.delete',
            'name' => 'Delete categories',
            'group' => 'Catalog',
            'description' => 'Delete catalog categories.',
        ],
        [
            'key' => 'admin.suppliers.create',
            'name' => 'Create suppliers',
            'group' => 'Catalog',
            'description' => 'Create supplier records.',
        ],
        [
            'key' => 'admin.suppliers.update',
            'name' => 'Update suppliers',
            'group' => 'Catalog',
            'description' => 'Update supplier records.',
        ],
        [
            'key' => 'admin.suppliers.delete',
            'name' => 'Delete suppliers',
            'group' => 'Catalog',
            'description' => 'Delete or deactivate supplier records.',
        ],
        [
            'key' => 'admin.orders.view',
            'name' => 'View orders',
            'group' => 'Orders',
            'description' => 'View admin order lists and order details.',
        ],
        [
            'key' => 'admin.orders.status.update',
            'name' => 'Update order status',
            'group' => 'Orders',
            'description' => 'Update fulfillment status for orders.',
        ],
        [
            'key' => 'admin.orders.payment.update',
            'name' => 'Update payment status',
            'group' => 'Orders',
            'description' => 'Update payment status for orders.',
        ],
        [
            'key' => 'admin.orders.bulk.update',
            'name' => 'Bulk update orders',
            'group' => 'Orders',
            'description' => 'Run bulk order status actions.',
        ],
        [
            'key' => 'admin.supplier.inventory.view',
            'name' => 'View supplier inventory portal',
            'group' => 'Supplier Portal',
            'description' => 'View the supplier inventory screen inside the admin shell.',
        ],
        [
            'key' => 'admin.supplier.requisitions.view',
            'name' => 'View supplier requisitions portal',
            'group' => 'Supplier Portal',
            'description' => 'View supplier requisition workflows inside the admin shell.',
        ],
        [
            'key' => 'admin.supplier.processing.view',
            'name' => 'View supplier processing portal',
            'group' => 'Supplier Portal',
            'description' => 'View supplier order processing workflows inside the admin shell.',
        ],
        [
            'key' => 'admin.supplier.orders.view',
            'name' => 'View supplier orders portal',
            'group' => 'Supplier Portal',
            'description' => 'View supplier order management inside the admin shell.',
        ],
        [
            'key' => 'admin.supplier.help.view',
            'name' => 'View supplier help portal',
            'group' => 'Supplier Portal',
            'description' => 'View supplier support content inside the admin shell.',
        ],
        [
            'key' => 'admin.warehouse.inventory.view',
            'name' => 'View warehouse inventory portal',
            'group' => 'Warehouse Portal',
            'description' => 'View warehouse inventory inside the admin shell.',
        ],
        [
            'key' => 'admin.warehouse.requisitions.view',
            'name' => 'View warehouse requisitions portal',
            'group' => 'Warehouse Portal',
            'description' => 'View warehouse requisition workflows inside the admin shell.',
        ],
        [
            'key' => 'admin.warehouse.fulfillment.view',
            'name' => 'View warehouse fulfillment portal',
            'group' => 'Warehouse Portal',
            'description' => 'View warehouse fulfillment workflows inside the admin shell.',
        ],
        [
            'key' => 'admin.warehouse.supplier_orders.view',
            'name' => 'View warehouse supplier orders portal',
            'group' => 'Warehouse Portal',
            'description' => 'View warehouse supplier order workflows inside the admin shell.',
        ],
        [
            'key' => 'admin.warehouse.help.view',
            'name' => 'View warehouse help portal',
            'group' => 'Warehouse Portal',
            'description' => 'View warehouse support content inside the admin shell.',
        ],
    ],
];
